ARG BASE_IMAGE="ubuntu:20.04"

FROM $BASE_IMAGE AS install_tools

LABEL "org.opencontainers.image.authors"='vprix team "info@vprix.com"'
LABEL "com.vprix.image"="true"


ARG START_XFCE4=0
ARG BG_IMG=bg_vprix.jpg
ARG DISTRO=ubuntu
ARG LANG='en_US.UTF-8'
ARG LANGUAGE='en_US:en'

ENV DISPLAY=:0 \
    VPRIX_PORT=8080 \
    VPRIX_USER="vprix-user" \
    VPRIX_AGENT_PATH=/usr/share/vprix_agent \
    HOME=/home/vprix-user \
    STARTUPDIR=/dockerstartup \
    INST_SCRIPTS=/dockerstartup/install \
    VNC_COL_DEPTH=24 \
    VNC_RESOLUTION=1280x1024 \
    VNC_PASSWORD=vprix.com \
    VNC_OPTIONS="-PreferBandwidth -DynamicQualityMin=4 -DynamicQualityMax=7 -DLP_ClipDelay=0" \
    SHELL=/bin/bash \
    START_XFCE4=$START_XFCE4 \
    LANG=$LANG \
    LANGUAGE=$LANGUAGE

EXPOSE $VPRIX_PORT

WORKDIR $HOME
RUN mkdir -p $HOME/Desktop

# 安装基础依赖
COPY ./src/ubuntu/install/tools $INST_SCRIPTS/tools/
## 正式编译的逻辑
RUN bash $INST_SCRIPTS/tools/install_tools.sh && rm -rf $INST_SCRIPTS/tools/
## 测试编译的逻辑
#RUN  cp /etc/apt/sources.list /etc/apt/sources.list.backup && \
#     cp $INST_SCRIPTS/tools/sources.list /etc/apt/sources.list && \
#     apt-get update && \
#     DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai apt-get -y install tzdata && \
#     apt-get install -y vim wget curl net-tools locales bzip2 wmctrl software-properties-common mesa-utils && \
#     apt-get clean -y


### 安装自定义字体
#COPY ./src/ubuntu/install/fonts $INST_SCRIPTS/fonts/
#RUN bash $INST_SCRIPTS/fonts/install_custom_fonts.sh && rm -rf $INST_SCRIPTS/fonts/


### 安装 xfce UI
COPY ./src/ubuntu/install/xfce $INST_SCRIPTS/xfce/
## 正式编译的逻辑
RUN bash $INST_SCRIPTS/xfce/install_xfce_ui.sh && rm -rf $INST_SCRIPTS/xfce/
### 测试编译的逻辑
#RUN  DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-terminal xterm xclip && \
#     apt-get clean -y


### 安装tigervnc组件
COPY ./src/ubuntu/install/tiger_vnc $INST_SCRIPTS/tiger_vnc/
## 正式编译的逻辑
RUN bash $INST_SCRIPTS/tiger_vnc/install_tiger_vnc.sh && rm -rf $INST_SCRIPTS/tiger_vnc/
## 测试编译的逻辑
#RUN  apt-get -y install tigervnc-standalone-server && \
#      apt-get clean -y

### Setup Container User - Libnss Wrapper
COPY ./src/ubuntu/install/libnss $INST_SCRIPTS/libnss/
RUN bash $INST_SCRIPTS/libnss/libnss_wrapper.sh  && rm -rf $INST_SCRIPTS/libnss/
## 测试编译的逻辑
#RUN  apt-get install -y libnss-wrapper gettext && \
#     apt-get clean -y && \
#     echo 'source $STARTUPDIR/generate_container_user' >> $HOME/.bashrc

### configure startup
ADD ./src/common/startup_scripts $STARTUPDIR
RUN bash $STARTUPDIR/set_user_permission.sh $STARTUPDIR $HOME

### 设置ui的配置信息和背景图
ADD ./src/$DISTRO/xfce/.config/ $HOME/.config/
RUN mkdir -p /usr/share/extra/backgrounds/
RUN mkdir -p /usr/share/extra/icons/
ADD /src/common/resources/images/bg_vprix.jpg  /usr/share/extra/backgrounds/bg_vprix.jpg
ADD /src/common/resources/images/$BG_IMG  /usr/share/extra/backgrounds/bg_default.jpg
ADD /src/common/resources/images/icon_ubuntu.png /usr/share/extra/icons/icon_ubuntu.png
ADD /src/common/resources/images/icon_vprix.png /usr/share/extra/icons/icon_vprix.png
ADD /src/common/resources/images/icon_vprix.png /usr/share/extra/icons/icon_default.png





### 安装vprix agent
COPY ./src/common/agent $VPRIX_AGENT_PATH/
RUN bash $VPRIX_AGENT_PATH/install_vprix_agent.sh && rm -rf $VPRIX_AGENT_PATH/install_vprix_agent.sh



#### 安装自定义鼠标指针
#COPY ./src/ubuntu/install/cursors $INST_SCRIPTS/cursors/
#RUN bash $INST_SCRIPTS/cursors/install_cursors.sh && rm -rf $INST_SCRIPTS/cursors/

COPY ./src/ubuntu/install/maximize_script $STARTUPDIR/

### 创建运行时用户
RUN (groupadd -g 1000 $VPRIX_USER \
    && useradd -M -u 1000 -g 1000 $VPRIX_USER \
    && usermod -a -G $VPRIX_USER $VPRIX_USER) ; exit 0
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

ENTRYPOINT ["/usr/share/vprix_agent/agent","--debug"]