ARG BASE_IMAGE="centos:centos7"

FROM $BASE_IMAGE AS install_tools

ARG DISTRO=centos
ARG START_XFCE4=0
ARG BG_IMG=bg_vprix.jpg
ARG LANG='en_US.UTF-8'
ARG LANGUAGE='en_US:en'

ENV DISPLAY=:0 \
    VPRIX_PORT=8080 \
    VPRIX_USER="vprix-user" \
    VPRIX_AGENT_PATH=/usr/share/vprix_agent \
    HOME=/home/vprix-user \
    STARTUPDIR=/dockerstartup \
    INST_SCRIPTS=/dockerstartup/install \
    VNC_COL_DEPTH=24 \
    VNC_RESOLUTION=1280x1024 \
    VNC_PASSWORD=vprix.com \
    VNC_OPTIONS="-PreferBandwidth -DynamicQualityMin=4 -DynamicQualityMax=7 -DLP_ClipDelay=0" \
    SHELL=/bin/bash \
    START_XFCE4=$START_XFCE4 \
    LANG=$LANG \
    LANGUAGE=$LANGUAGE

EXPOSE $VPRIX_PORT

WORKDIR $HOME
RUN mkdir -p $HOME/Desktop

# 安装基础依赖
COPY ./src/ubuntu/install/tools $INST_SCRIPTS/tools/
## 正式编译的逻辑
#RUN bash $INST_SCRIPTS/tools/install_tools.sh && rm -rf $INST_SCRIPTS/tools/
## 测试编译的逻辑
RUN yum -y install deltarpm  && \
    yum -y install epel-release && \
    yum -y update && \
    yum -y install vim  wget which net-tools bzip2 \
    && yum clean all && rm -rf /tmp/*


## 安装自定义字体
COPY ./src/ubuntu/install/fonts $INST_SCRIPTS/fonts/
#RUN bash $INST_SCRIPTS/fonts/install_custom_fonts.sh && rm -rf $INST_SCRIPTS/fonts/
## 测试编译的逻辑
RUN  yum install -y wqy-zenhei-fonts && \
      yum clean all && rm -rf /tmp/*

### 安装 xfce UI
COPY ./src/ubuntu/install/xfce $INST_SCRIPTS/xfce/
## 正式编译的逻辑
#RUN bash $INST_SCRIPTS/xfce/install_xfce_ui.sh && rm -rf $INST_SCRIPTS/xfce/
## 测试编译的逻辑
RUN yum --enablerepo=epel -y -x gnome-keyring --skip-broken groups install "Xfce"  && \
    yum -y groups install "Fonts" && \
    yum erase -y *power* *screensaver* && \
    yum clean all && \
    rm /etc/xdg/autostart/xfce-polkit* && \
    /bin/dbus-uuidgen > /etc/machine-id


### 安装tigervnc组件
COPY ./src/ubuntu/install/tiger_vnc $INST_SCRIPTS/tiger_vnc/
## 正式编译的逻辑
#RUN bash $INST_SCRIPTS/tiger_vnc/install_tiger_vnc.sh && rm -rf $INST_SCRIPTS/tiger_vnc/
## 测试编译的逻辑
RUN yum -y install \
         tigervnc-server \
         tigervnc-server-module \
         xinetd \
    && yum clean all && rm -rf /tmp/*


### 设置ui的配置信息和背景图
ADD ./src/$DISTRO/xfce/.config/ $HOME/.config/
RUN mkdir -p /usr/share/extra/backgrounds/
RUN mkdir -p /usr/share/extra/icons/
ADD /src/common/resources/images/$BG_IMG  /usr/share/extra/backgrounds/bg_default.jpg
ADD /src/common/resources/images/icon_vprix.png /usr/share/extra/icons/icon_default.png


### 安装自定义鼠标指针
COPY ./src/ubuntu/install/cursors $INST_SCRIPTS/cursors/
RUN bash $INST_SCRIPTS/cursors/install_cursors.sh && rm -rf $INST_SCRIPTS/cursors/


### 安装vprix agent
COPY ./src/common/agent $VPRIX_AGENT_PATH/
RUN bash $VPRIX_AGENT_PATH/install_vprix_agent.sh && rm -rf $VPRIX_AGENT_PATH/install_vprix_agent.sh



### 创建运行时用户
RUN (groupadd -g 1000 $VPRIX_USER \
    && useradd -M -u 1000 -g 1000 $VPRIX_USER \
    && usermod -a -G $VPRIX_USER $VPRIX_USER) ; exit 0
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

#USER 1000

ENTRYPOINT ["/usr/share/vprix_agent/agent","--debug"]